# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aoctl < Formula
  desc "Advent of Code CLI to help you organize and test your solutions"
  homepage "https://pkg.go.dev/github.com/dolfolife/aoctl"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.10/aoctl_Darwin_x86_64.tar.gz"
      sha256 "03b47b9ff79d83237f48e557a8e06eb343312ab6a368581b0ea47d326dfb6c1c"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.10/aoctl_Darwin_arm64.tar.gz"
      sha256 "031630480164785e86c0c4678e35a4699092a034f244d61ac7a3c36630ee8ab6"

      def install
        bin.install "aoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.10/aoctl_Linux_armv6.tar.gz"
      sha256 "04d14dcab026028eef4df64f54227d51b1e608b7057c44824ba16d807c50f329"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.10/aoctl_Linux_x86_64.tar.gz"
      sha256 "d353758bda9d7809e363ceb3b40d27164d255b7cb5827364bb2fb72236b09b10"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.10/aoctl_Linux_arm64.tar.gz"
      sha256 "460db5ead8c25090d7c8ebbcc1f337ca7e6dae0b1156a55b03834a75b25547c7"

      def install
        bin.install "aoctl"
      end
    end
  end

  test do
    system "#{bin}/aoctl --help"
  end
end
