# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aoctl < Formula
  desc "Advent of Code CLI to help you organize and test your solutions"
  homepage "https://github.com/dolfolife/aoctl"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.7/aoctl_Darwin_x86_64.tar.gz"
      sha256 "fa53fbde4a7e5b52e7da7ca5cf80578b606cb180d01b1fd4de391de2b82d9133"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.7/aoctl_Darwin_arm64.tar.gz"
      sha256 "360465c414e34ba255be562d504ba29b97c3b7f538acf4ab8591c228a5eb0a60"

      def install
        bin.install "aoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.7/aoctl_Linux_x86_64.tar.gz"
      sha256 "c73d5335b2b57ded3ad946a1a6a2818496e1bf5abe4a7da3c3e692cc728b7601"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.7/aoctl_Linux_armv6.tar.gz"
      sha256 "6617ed122671051951ebb88834b9cb41d19b84ff12e553fc96d82f1dcbfce30a"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.7/aoctl_Linux_arm64.tar.gz"
      sha256 "3fbc5240f720f51c288f9dc536eca8dbcf421c30a69f8408b9e56dc04a622b2d"

      def install
        bin.install "aoctl"
      end
    end
  end

  test do
    system "#{bin}/aoctl --help"
  end
end
